getContent = function () {
  return [
    {
      title:"Western Dragon",
      summary:"An origami dragon of high intermediate complexity. All fold angles are multiples of 22.5 degrees and relatively few folds are more than 2-ply. This makes it easier to retain accuracy and fold from a small square. The long limbs also make a variety of poses possible.",
      tags: ['origami', 'uniaxial', '22.5', 'dragon', 'tutorial'],
      img:"img/dragon_CP.svg",
      link:"https://caseyshields.github.io/dragon/"
      // TODO add a list of dates to each entry...
    }, {
      title:"Light Tank",
      summary:"A lego mech which transforms into a light wheeled tank based on the Japanese MCV Type 16. Working gun and mortars are usable in both robot and vehicle mode. Originally released on the old brick link MOC pages.",
      tags: ['lego', 'transformer', 'tank'],
      img:"tank/tank.png",
      link:"tank/index.html"
    }, {
      title:"Right Angle Fractal",
      summary:"Nested semi-circles inscribed with right angles. SVG generated by short Js program.",
      tags: ['fractal', 'origami', 'svg'],
      img:"rightangle/rightangle.svg",
      link:"rightangle/index.html"
    }, {
      title:"Beam Trooper",
      summary:"Mobile Frame Zero is a miniatures war game where you use your legos to build terrain, robots, weapons and inventory. This mobile frame has a beam rifle and jet pack.",
      tags:['lego', 'MFZ', 'games'],
      img:"img/beamtrooper.png",
      link: "https://www.bricklink.com/v3/studio/design.page?idModel=44830"
    },{
      title: "Trie Example",
      summary: "An example of D3's force layout. Type words into the box and hit enter to add them to the trie. Or just press enter to add default inputs.",
      tags: ['D3', 'trie', 'algorithms'],
      img: "img/trie.svg",
      link: "https://caseyshields.github.io/trie/"
    },{
    //   title: "Henderson Gallery",
    //   summary: "Part of the submission process for the gallery in Henderson's city hall is an artist statement. I've been thinking about some of this stuff for awhile and I think I summed up my thoughts okay. But is it pretentious enough? I really need to distract from my terrible photography.",
    //   tags: ['origami', 'essay', 'art'],
    //   img: "cityhall/hallDualFrames.JPG",
    //   link: "cityhall/index.html"
    // },{
      title: "Ladder Diagrams",
      summary: "An attempt to make a re-usable D3 component for ladder diagrams.",
      tags: ['D3', 'ladder', 'component'],
      img: "img/ladder.svg",
      link: "https://caseyshields.github.io/ladder/"
    },{
      title: "Star Catalog",
      summary: "Playing around with projections in D3 using the FK6 star catalog.",
      tags: ['D3', 'astronomy', 'FK6', 'code', 'component'],
      img: "img/stars.png",
      link: "https://caseyshields.github.io/starmap/"
    },{
      title: "Rocket Swordsman",
      summary: "Made another figurine for MF0. Rocket propelled swordsman.",
      tags: ['MFZ','lego','mech'],
      img: "img/rocketswordsman.png",
      link: "https://www.bricklink.com/v3/studio/design.page?idModel=48368"
      
    }, {
      title: "Polar Plot",
      summary: "Quick demo of a simple polar plot component. Exercises some mouse limited interactivity and gives some css styling ideas.",
      tags: ['D3', 'component', 'code'],
      img: "img/polar.svg",
      link: "https://caseyshields.github.io/polar/"
    }, {
      title: "Nevada",
      summary: "Made a layered vector map component with D3.",
      tags: ['D3', 'code', 'component'],
      img: 'img/nevada.svg',
      link: "https://caseyshields.github.io/nevada/"
    }, {
      title: "Scout",
      summary: "Mobile Frame Zero scouting mech with a sniper rifle.",
      tags: ['MFZ', 'lego', 'mech'],
      img: "img/sniperscout.png",
      link: "https://www.bricklink.com/v3/studio/design.page?idModel=65471"
    }, {
      title: "Pistoleer",
      summary: "Mobile Frame with enhanced sensors and dual pistols.",
      tags: ['MFZ', 'lego', 'mech'],
      img: "img/pistoleer.png",
      link: "https://www.bricklink.com/v3/studio/design.page?idModel=66607"
    }, {
      title: "Dragon Tutorial",
      summary: "A first attempt at making an origami tutorial.",
      tags: ['origami', 'youtube', 'dragon'],
      img: "img/dragon.svg",
      link: "https://youtu.be/kOzWXQF8Z68"
    }, {
      title: "Suffix Trie",
      summary: "Working through some examples from Ukkonen's lectures on suffix trees.",
      tags: ['algorithms', 'trie', 'D3'],
      link: "https://caseyshields.github.io/suffix"
    }
  ]
};