getContent = function () {
  return [
    {
      title:"Western Dragon",
      name:"dragon",
      summary:"An origami dragon of high intermediate complexity. All fold angles are multiples of 22.5 degrees and relatively few folds are more than 2-ply. This makes it easier to retain accuracy and fold from a small square. The long limbs also make a variety of poses possible.",
      tags: ['origami', 'uniaxial', '12.5', 'dragon'],
      img:"dragon/dragon.svg",
      link:"https://caseyshields.github.io/dragon/"
    }, {
      title:"Light Tank",
      name:"tank",
      summary:"A lego mech which transforms into a light wheeled tank based on the Japanese MCV Type 16. Working gun and mortars are usable in both robot and vehicle mode. Originally released on the old brick link MOC pages.",
      tags: ['lego', 'transformer', 'tank'],
      img:"tank/tank.png",
      link:"tank/index.html"
    }, {
      title:"Right Angle Fractal",
      name:"rightangle",
      summary:"Nested semi-circles inscribed with right angles. SVG generated by short Js program.",
      tags: ['fractal', 'origami', 'svg'],
      img:"rightangle/rightangle.svg",
      link:"rightangle/index.html"
    }, {
      title:"Beam Trooper",
      name:"beamtrooper",
      summary:"Mobile Frame Zero is a miniatures war game where you use your legos to build terrain, robots, weapons and inventory. This mobile frame has a beam rifle and jet pack.",
      tags:['lego', 'MFZ', 'games'],
      img:"beamtrooper/beamtrooper.png",
      link:"https://studio.bricklink.com/v2/build/model.page?idModel=44830"
    },{
      title: "Trie Example",
      name: "trie",
      summary: "An example of D3's force layout. Type words into the box and hit enter to add them to the trie. Or just press enter to add default inputs.",
      tags: ['D3', 'trie', 'code'],
      img: "trie/trie.svg",
      link: "https://caseyshields.github.io/trie/"
    },{
      title: "Henderson City Hall Gallery",
      name: "cityhall",
      summary: "Part of the submission process for the gallery in Henderson's city hall is an artist statement. I've been thinking about some of this stuff for awhile and I think I summed up my thoughts okay. But is it pretentious enough? I really need to distract from my terrible photography.",
      tags: ['origami', 'essay', 'art'],
      img: "cityhall/hallDualFrames.JPG",
      link: "cityhall/index.html"
    },{
      title: "Ladder Diagrams",
      name: "ladder",
      summary: "An attempt to make a re-usable D3 component for ladder diagrams.",
      tags: ['D3', 'ladder', 'code'],
      img: "ladder/ladder.svg",
      link: "https://caseyshields.github.io/ladder/"
    },{
      title: "Star Catalog",
      name: "starlog",
      summary: "Playing around with projections in D3 using the FK6 star catalog.",
      tags: ['D3', 'astronomy', 'FK6', 'code'],
      img: "starlog/stars.png",
      link: "https://caseyshields.github.io/starmap/"
    },{
      title: "MFZ Rocket Swordsman",
      name: "rocketswordsman",
      summary: "Made another figurine for MF0. Rocket propelled swordsman. I can't really elaborate more.",
      tags: ['MFZ','lego','mech'],
      img: "mfz/rocketswordsman.png",
      link: "https://studio.bricklink.com/v2/build/model.page?idModel=48368"
    }
  ]
};